package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

type Model struct {
	Package string
	Alias   string
	Type    string
}

var (
	foundModels []Model
	driver      = flag.String("driver", "postgres", "имя драйвера")
)

func main() {
	pkgConfig := &packages.Config{
		Mode: packages.NeedFiles |
			packages.NeedCompiledGoFiles |
			packages.NeedName |
			packages.NeedSyntax,
		Dir: ".",
	}

	pkgs, err := packages.Load(pkgConfig, "./...")
	if err != nil {
		panic(err)
	}

	for _, pkg := range pkgs {
		if len(pkg.Errors) > 0 {
			continue
		}

		alias := filepath.Base(pkg.PkgPath)

		for _, file := range pkg.Syntax {

			for _, decl := range file.Decls {

				genDecl, ok := decl.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE {
					continue
				}

				for _, spec := range genDecl.Specs {

					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}

					structType, ok := typeSpec.Type.(*ast.StructType)
					if !ok {
						continue
					}

					if !hasGormModel(structType) {
						continue
					}

					foundModels = append(foundModels, Model{
						Package: pkg.PkgPath,
						Alias:   alias,
						Type:    typeSpec.Name.Name,
					})
				}
			}
		}
	}

	if len(foundModels) == 0 {
		fmt.Println("no gorm models found")
		return
	}

	if err = generateFile(foundModels); err != nil {
		panic(err)
	}

	fmt.Println("models_gen.go generated successfully")

	cmd := exec.Command("go", "run", "./models_gen.go")
	cmd.Dir = "."

	if err = cmd.Run(); err != nil {
		return
	}
}

func hasGormModel(st *ast.StructType) bool {
	for _, field := range st.Fields.List {

		if field.Names != nil {
			continue
		}

		switch t := field.Type.(type) {

		case *ast.SelectorExpr:
			if ident, ok := t.X.(*ast.Ident); ok {
				if ident.Name == "gorm" && t.Sel.Name == "Model" {
					return true
				}
			}

		case *ast.Ident:
			if t.Name == "Model" {
				return true
			}

		}
	}

	return false
}

func generateFile(models []Model) error {
	file, err := os.Create("models_gen.go")
	if err != nil {
		return err
	}
	defer file.Close()

	builder := strings.Builder{}

	builder.WriteString(`// Code generated by gorm.migrateloader DO NOT EDIT.
// Version: v0.0.1

// Built By: go install
`)
	builder.WriteString("package main\n\n")

	builder.WriteString("import (\n")

	imports := map[string]string{}

	for _, m := range models {
		imports[m.Package] = m.Alias
	}

	for path, alias := range imports {
		builder.WriteString(fmt.Sprintf("\t%s \"%s\"\n", alias, path))
	}

	builder.WriteString(`
    "fmt"
	"io"
	"os"

	"ariga.io/atlas-provider-gorm/gormschema"
`)

	builder.WriteString(")\n\n")

	builder.WriteString("var Models = []any{\n")

	for _, m := range models {
		builder.WriteString(fmt.Sprintf("\t&%s.%s{},\n", m.Alias, m.Type))
	}

	builder.WriteString("}\n")

	builder.WriteString(fmt.Sprintf(`
func main() {
	stmts, err := gormschema.New("%s").Load(Models...)
	if err != nil {
`, *driver))

	builder.WriteString(`
		fmt.Fprintf(os.Stderr, "failed to load gorm schema: %v\n", err)
		os.Exit(1)
	}
	
	if _, err = io.WriteString(os.Stdout, stmts); err != nil {
		panic(err)
	}
}
`)

	_, err = file.WriteString(builder.String())
	return err
}
